#! /usr/bin/bash

rm /tmp/mdebug* /tmp/flight_times_*  /tmp/start


export MERCURY_ROOT=${HOME}/mercury
export GOPATH=${MERCURY_ROOT}

go run ./*.go    ./scripts/tests/latency/telco_latency/200

#go run ./*.go    ./scripts/demos/00



