#! /bin/bash

# Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# NOTE: the following environment variables are serving suggestions. 
# Alter as desired, and use them in your ~/.bashrc, or directly
# in this file.

export MERCURY_ROOT=${HOME}/mercury
export DISPATCH_INSTALL_ROOT=${HOME}/latest/install/dispatch
export PROTON_INSTALL_ROOT=${HOME}/latest/install/proton

export GOPATH=${MERCURY_ROOT}

#go run ./test_03.go -name test_03 -id `date +%Y_%m_%d` 

# If it doesn't work, turn on verbosity so you can see all
# the environment variables and commands : 
go run ./test_03.go -name test_03 -id `date +%Y_%m_%d` -verbose
  


