#! /bin/bash



export MERCURY_ROOT=${HOME}/mercury
export DISPATCH_INSTALL_ROOT=${HOME}/latest/install/dispatch
export PROTON_INSTALL_ROOT=${HOME}/latest/install/proton

export GOPATH=${MERCURY_ROOT}

#go run ./test_03.go -name test_03 -id `date +%Y_%m_%d` 

# If it doesn't work, turn on verbosity so you can see all
# the environment variables and commands : 
go run ./test_qdstat_output.go


