#! /usr/bin/bash

export MERCURY_ROOT=${HOME}/mercury
export GOPATH=${MERCURY_ROOT}





echo "MESSAGE SIZE"
sleep 5
go run ./message_size.go 


#echo "LINEAR"
#sleep 5
#go run ./linear.go 




# echo "HORIZONTAL"
# sleep 5
# go run ./horizontal.go



